apiVersion: v1
kind: Service
metadata:
  name: aicallsimulator-service
spec:
  selector:
    app: aicallsimulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Kind translates this to NodePort
